apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  labels:
    app: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: stock
        image: ropa1998/stock-service:latest
        ports:
        - containerPort: 40041
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stock
  name: stock
spec:
  selector:
    app: stock
  ports:
    - port: 9090